// Kaya Games — curated Question-of-the-Day bank (2026-07-19).
//
// 120 hand-picked, kid-friendly questions across the weekly subject rhythm
// (Sun faith & family · Mon science · Tue geography · Wed animals · Thu
// numbers · Fri words · Sat sports & fun). This is the ALWAYS-WORKS pool:
// the daily rotation prefers fresh AI questions, but when generation is
// unavailable this bank keeps QotD interesting for ~4 months without a
// repeat (the rotation's `seen` fingerprint list guarantees no-repeat).
//
// NOTE the correct answer is deliberately spread across positions 0–3 —
// the old 8-question fallback always put it first, which kids spot fast.

export interface QotdBankItem {
  q: string;
  choices: [string, string, string, string];
  answer: number;        // 0-based index of the correct choice
  context: string;       // playful chip text
  fact: string;          // "Did you know?" follow-up
  subject: string;
}

export const QOTD_BANK: QotdBankItem[] = [
  // ── 🔬 Science (20) ────────────────────────────────────────────────
  { q: 'Which planet is called the Red Planet?', choices: ['Venus', 'Mars', 'Jupiter', 'Saturn'], answer: 1, context: '🪐 Out in space…', fact: 'Did you know? Mars looks red because its soil is full of rusty iron dust.', subject: 'science' },
  { q: 'What do plants need to make their own food?', choices: ['Moonlight', 'Wind', 'Sunlight', 'Thunder'], answer: 2, context: '🌱 In the garden…', fact: 'Did you know? Plants turn sunlight, water and air into food — it’s called photosynthesis.', subject: 'science' },
  { q: 'What is frozen water called?', choices: ['Steam', 'Ice', 'Fog', 'Dew'], answer: 1, context: '❄️ In the freezer…', fact: 'Did you know? Ice floats because it is lighter than liquid water — that’s unusual for a solid!', subject: 'science' },
  { q: 'Which part of your body pumps blood?', choices: ['Lungs', 'Brain', 'Stomach', 'Heart'], answer: 3, context: '🫀 Inside you…', fact: 'Did you know? Your heart beats about 100,000 times every single day.', subject: 'science' },
  { q: 'What gas do we breathe in to stay alive?', choices: ['Oxygen', 'Helium', 'Smoke', 'Carbon dioxide'], answer: 0, context: '🌬️ Take a deep breath…', fact: 'Did you know? The oxygen we breathe is mostly made by plants and tiny ocean algae.', subject: 'science' },
  { q: 'Which is the closest star to Earth?', choices: ['The Moon', 'Polaris', 'The Sun', 'Venus'], answer: 2, context: '☀️ Look up…', fact: 'Did you know? Sunlight takes about 8 minutes to travel from the Sun to your eyes.', subject: 'science' },
  { q: 'What do you call molten rock that erupts from a volcano?', choices: ['Lava', 'Mud', 'Hail', 'Ash'], answer: 0, context: '🌋 Rumble rumble…', fact: 'Did you know? Lava can be five times hotter than a kitchen oven at full power.', subject: 'science' },
  { q: 'Which of these is a source of light?', choices: ['A mirror', 'The Moon', 'A firefly', 'A shadow'], answer: 2, context: '💡 Bright ideas…', fact: 'Did you know? Fireflies make their own light with a chemical reaction in their bodies — with almost no heat.', subject: 'science' },
  { q: 'What force pulls things down to the ground?', choices: ['Magnetism', 'Gravity', 'Electricity', 'Friction'], answer: 1, context: '🍎 Watch it fall…', fact: 'Did you know? Gravity on the Moon is 6 times weaker — you could jump 6 times higher there!', subject: 'science' },
  { q: 'Which of these animals is a mammal?', choices: ['Crocodile', 'Eagle', 'Shark', 'Dolphin'], answer: 3, context: '🔬 Think carefully…', fact: 'Did you know? Dolphins are mammals like us — they breathe air and feed their babies milk.', subject: 'science' },
  { q: 'What does a thermometer measure?', choices: ['Weight', 'Temperature', 'Speed', 'Sound'], answer: 1, context: '🌡️ Hot or cold…', fact: 'Did you know? The hottest air temperature ever recorded on Earth was about 57°C, in Death Valley.', subject: 'science' },
  { q: 'How many bones does a newborn baby have compared to an adult?', choices: ['Fewer', 'More', 'The same', 'None'], answer: 1, context: '🦴 Growing up…', fact: 'Did you know? Babies are born with about 300 bones; many fuse together to leave adults with 206.', subject: 'science' },
  { q: 'What do caterpillars turn into?', choices: ['Bees', 'Dragonflies', 'Butterflies', 'Beetles'], answer: 2, context: '🐛 A big change…', fact: 'Did you know? Inside its chrysalis, a caterpillar almost completely dissolves before rebuilding as a butterfly.', subject: 'science' },
  { q: 'Which planet has the famous rings around it?', choices: ['Mercury', 'Earth', 'Mars', 'Saturn'], answer: 3, context: '🪐 Ring ring…', fact: 'Did you know? Saturn’s rings are made of billions of pieces of ice and rock, some as small as sand.', subject: 'science' },
  { q: 'What is the boiling point of water at sea level?', choices: ['50°C', '100°C', '150°C', '200°C'], answer: 1, context: '🫖 In the kitchen…', fact: 'Did you know? On top of Mount Kilimanjaro water boils at only about 80°C because the air is thinner.', subject: 'science' },
  { q: 'Which body part helps you smell?', choices: ['Ears', 'Nose', 'Elbows', 'Knees'], answer: 1, context: '👃 Sniff sniff…', fact: 'Did you know? Your nose can remember around 50,000 different smells.', subject: 'science' },
  { q: 'What is a group of stars that makes a picture called?', choices: ['A galaxy', 'A comet', 'A constellation', 'A planet'], answer: 2, context: '✨ Connect the dots…', fact: 'Did you know? People have been naming star pictures for thousands of years — like the Southern Cross seen from Tanzania.', subject: 'science' },
  { q: 'Which of these materials is magnetic?', choices: ['Wood', 'Plastic', 'Glass', 'Iron'], answer: 3, context: '🧲 Stick to it…', fact: 'Did you know? The Earth itself is a giant magnet — that’s how compasses find north.', subject: 'science' },
  { q: 'What do we call animals that only eat plants?', choices: ['Herbivores', 'Carnivores', 'Omnivores', 'Insectivores'], answer: 0, context: '🥬 Dinner time…', fact: 'Did you know? An elephant is a herbivore that eats up to 150 kg of plants every day.', subject: 'science' },
  { q: 'Why do we see lightning before we hear thunder?', choices: ['Light travels faster than sound', 'Thunder is shy', 'Sound travels faster', 'Our ears are slow'], answer: 0, context: '⛈️ Storm watch…', fact: 'Did you know? Count the seconds between flash and boom — every 3 seconds means the storm is about 1 km away.', subject: 'science' },

  // ── 🌍 Geography (20) ──────────────────────────────────────────────
  { q: 'Which is the tallest mountain in Africa?', choices: ['Mount Kenya', 'Kilimanjaro', 'Atlas', 'Table Mountain'], answer: 1, context: '🏔️ Right at home…', fact: 'Did you know? Kilimanjaro is in Tanzania and has snow on top even though it sits near the equator.', subject: 'geography' },
  { q: 'Which is the largest continent?', choices: ['Africa', 'Europe', 'Asia', 'Australia'], answer: 2, context: '🗺️ Around the world…', fact: 'Did you know? Asia is home to more than half of all the people on Earth.', subject: 'geography' },
  { q: 'What is the longest river in the world?', choices: ['The Nile', 'The Amazon', 'The Congo', 'The Mississippi'], answer: 0, context: '🚣 Down the river…', fact: 'Did you know? The Nile flows through 11 African countries on its way to the Mediterranean Sea.', subject: 'geography' },
  { q: 'Which desert is the largest hot desert on Earth?', choices: ['Kalahari', 'Gobi', 'Namib', 'Sahara'], answer: 3, context: '🏜️ Feeling thirsty…', fact: 'Did you know? The Sahara is almost as big as the whole United States.', subject: 'geography' },
  { q: 'What is the capital city of Tanzania?', choices: ['Dar es Salaam', 'Dodoma', 'Arusha', 'Mwanza'], answer: 1, context: '🇹🇿 Home ground…', fact: 'Did you know? Dodoma became the official capital in 1974, though Dar es Salaam is still the biggest city.', subject: 'geography' },
  { q: 'Which ocean touches the coast of Tanzania?', choices: ['Atlantic', 'Pacific', 'Indian', 'Arctic'], answer: 2, context: '🌊 At the beach…', fact: 'Did you know? Warm Indian Ocean water is why Zanzibar’s beaches feel like a bath.', subject: 'geography' },
  { q: 'What do we call a piece of land surrounded by water on all sides?', choices: ['A peninsula', 'An island', 'A valley', 'A cliff'], answer: 1, context: '🏝️ Water everywhere…', fact: 'Did you know? Greenland is the world’s largest island — but it’s mostly covered in ice, not green at all.', subject: 'geography' },
  { q: 'Which imaginary line divides the Earth into North and South halves?', choices: ['The horizon', 'The prime meridian', 'The equator', 'The tropic'], answer: 2, context: '🌐 Slice the globe…', fact: 'Did you know? The equator passes through 13 countries — and it’s hot there all year round.', subject: 'geography' },
  { q: 'Which is the largest lake in Africa?', choices: ['Lake Victoria', 'Lake Tanganyika', 'Lake Malawi', 'Lake Chad'], answer: 0, context: '🐟 Big waters…', fact: 'Did you know? Lake Victoria is shared by Tanzania, Uganda and Kenya — and is the source of the Nile.', subject: 'geography' },
  { q: 'What is the biggest country in the world by land?', choices: ['China', 'Canada', 'USA', 'Russia'], answer: 3, context: '🗺️ Think BIG…', fact: 'Did you know? Russia is so wide it covers 11 time zones — breakfast on one side is bedtime on the other.', subject: 'geography' },
  { q: 'Which famous waterfall sits between Zambia and Zimbabwe?', choices: ['Niagara Falls', 'Victoria Falls', 'Angel Falls', 'Tugela Falls'], answer: 1, context: '💦 The smoke that thunders…', fact: 'Did you know? Locals call Victoria Falls "Mosi-oa-Tunya" — the smoke that thunders.', subject: 'geography' },
  { q: 'What are the Serengeti plains famous for?', choices: ['Skyscrapers', 'The Great Migration', 'Volcanoes', 'Deserts'], answer: 1, context: '🦓 On safari…', fact: 'Did you know? Over a million wildebeest cross the Serengeti every year in the Great Migration.', subject: 'geography' },
  { q: 'Which country is shaped like a boot?', choices: ['Spain', 'Egypt', 'Italy', 'India'], answer: 2, context: '👢 Look at the map…', fact: 'Did you know? Italy’s boot even has a "ball" to kick — the island of Sicily at its toe.', subject: 'geography' },
  { q: 'What is the coldest continent?', choices: ['Antarctica', 'Europe', 'North America', 'Asia'], answer: 0, context: '🥶 Brrr…', fact: 'Did you know? Antarctica once recorded −89°C — the coldest temperature ever measured on Earth.', subject: 'geography' },
  { q: 'Which city is called the Big Apple?', choices: ['London', 'Paris', 'Tokyo', 'New York'], answer: 3, context: '🍎 City lights…', fact: 'Did you know? More than 800 languages are spoken in New York — the most of any city.', subject: 'geography' },
  { q: 'The Great Pyramids are found in which country?', choices: ['Kenya', 'Egypt', 'Morocco', 'Greece'], answer: 1, context: '🐫 Ancient wonders…', fact: 'Did you know? The Great Pyramid was the tallest building in the world for almost 4,000 years.', subject: 'geography' },
  { q: 'What do we call the hot melted rock deep inside the Earth?', choices: ['Soil', 'Magma', 'Sand', 'Coal'], answer: 1, context: '🌋 Deep down…', fact: 'Did you know? The Earth’s core is about as hot as the surface of the Sun.', subject: 'geography' },
  { q: 'Which island off Tanzania is famous for spices?', choices: ['Madagascar', 'Comoros', 'Zanzibar', 'Seychelles'], answer: 2, context: '🌶️ Spice route…', fact: 'Did you know? Zanzibar was once the world’s biggest producer of cloves.', subject: 'geography' },
  { q: 'How many continents are there?', choices: ['5', '6', '7', '8'], answer: 2, context: '🌍 Count them up…', fact: 'Did you know? Africa is the only continent crossed by both the equator and the prime meridian.', subject: 'geography' },
  { q: 'What is a very tall wave caused by an undersea earthquake called?', choices: ['A ripple', 'A tsunami', 'A tide', 'A current'], answer: 1, context: '🌊 Ocean power…', fact: 'Did you know? In the deep ocean a tsunami can travel as fast as a jet plane.', subject: 'geography' },

  // ── 🦁 Animals (20) ────────────────────────────────────────────────
  { q: 'Which animal is called the King of the Jungle?', choices: ['Elephant', 'Lion', 'Tiger', 'Gorilla'], answer: 1, context: '🦁 Hear the roar…', fact: 'Did you know? A lion’s roar can be heard 8 kilometres away.', subject: 'animals' },
  { q: 'Which is the fastest land animal?', choices: ['Cheetah', 'Horse', 'Ostrich', 'Antelope'], answer: 0, context: '💨 Ready, set, go…', fact: 'Did you know? A cheetah can reach 100 km/h in just 3 seconds — faster than most cars.', subject: 'animals' },
  { q: 'Which bird cannot fly but runs very fast?', choices: ['Parrot', 'Eagle', 'Ostrich', 'Owl'], answer: 2, context: '🪶 Wings or legs…', fact: 'Did you know? An ostrich egg is so strong an adult can stand on it without breaking it.', subject: 'animals' },
  { q: 'What is the biggest animal that has ever lived?', choices: ['African elephant', 'Blue whale', 'T-rex', 'Giraffe'], answer: 1, context: '🐋 Deep blue…', fact: 'Did you know? A blue whale’s heart is the size of a small car.', subject: 'animals' },
  { q: 'How do bees tell each other where flowers are?', choices: ['By dancing', 'By singing', 'By writing', 'By pointing'], answer: 0, context: '🐝 Busy bees…', fact: 'Did you know? A bee’s "waggle dance" tells other bees the exact direction and distance to the flowers.', subject: 'animals' },
  { q: 'Which animal sleeps standing up most of the time?', choices: ['Dog', 'Cat', 'Horse', 'Pig'], answer: 2, context: '😴 Nap time…', fact: 'Did you know? Horses lock their leg joints so they can doze standing without falling over.', subject: 'animals' },
  { q: 'What is a baby goat called?', choices: ['A cub', 'A kid', 'A calf', 'A chick'], answer: 1, context: '🐐 On the farm…', fact: 'Did you know? Goat kids can stand and take their first steps within minutes of being born.', subject: 'animals' },
  { q: 'Which animal changes colour to hide?', choices: ['Chameleon', 'Zebra', 'Hippo', 'Crocodile'], answer: 0, context: '🎨 Now you see me…', fact: 'Did you know? Chameleons also change colour to show their mood — dark when upset, bright when happy.', subject: 'animals' },
  { q: 'How many hearts does an octopus have?', choices: ['1', '2', '3', '5'], answer: 2, context: '🐙 Under the sea…', fact: 'Did you know? An octopus has 3 hearts and blue blood — and can squeeze through a hole the size of a coin.', subject: 'animals' },
  { q: 'Which big cat has stripes?', choices: ['Lion', 'Leopard', 'Cheetah', 'Tiger'], answer: 3, context: '🐯 Spot the difference…', fact: 'Did you know? Every tiger’s stripe pattern is unique, like a human fingerprint.', subject: 'animals' },
  { q: 'What do pandas eat almost all day?', choices: ['Fish', 'Bamboo', 'Honey', 'Grass'], answer: 1, context: '🐼 Crunch crunch…', fact: 'Did you know? A panda spends up to 14 hours a day eating bamboo.', subject: 'animals' },
  { q: 'Which animal carries its baby in a pouch?', choices: ['Kangaroo', 'Elephant', 'Monkey', 'Rhino'], answer: 0, context: '🦘 Hop hop…', fact: 'Did you know? A newborn kangaroo is only the size of a grape when it climbs into the pouch.', subject: 'animals' },
  { q: 'What is a group of lions called?', choices: ['A herd', 'A pack', 'A pride', 'A flock'], answer: 2, context: '🦁 Family matters…', fact: 'Did you know? In a lion pride, the lionesses do most of the hunting — as a team.', subject: 'animals' },
  { q: 'Which sea creature has 8 arms?', choices: ['Starfish', 'Jellyfish', 'Crab', 'Octopus'], answer: 3, context: '🌊 Count the arms…', fact: 'Did you know? Each octopus arm has its own mini-brain and can taste what it touches.', subject: 'animals' },
  { q: 'Which animal is the tallest in the world?', choices: ['Elephant', 'Giraffe', 'Camel', 'Horse'], answer: 1, context: '🦒 Head in the clouds…', fact: 'Did you know? A giraffe’s neck has the same number of bones as yours — just much, much longer.', subject: 'animals' },
  { q: 'What do you call an animal that is active at night?', choices: ['Nocturnal', 'Tropical', 'Seasonal', 'Natural'], answer: 0, context: '🌙 Night shift…', fact: 'Did you know? Owls can turn their heads almost all the way around to see in the dark.', subject: 'animals' },
  { q: 'Which insect makes silk?', choices: ['Ant', 'Silkworm', 'Beetle', 'Wasp'], answer: 1, context: '🧵 Spinning…', fact: 'Did you know? One silkworm cocoon can unravel into a thread nearly 1 kilometre long.', subject: 'animals' },
  { q: 'Where do polar bears live?', choices: ['Antarctica', 'The Arctic', 'The Sahara', 'The Amazon'], answer: 1, context: '🐻‍❄️ Ice ice baby…', fact: 'Did you know? Polar bear fur isn’t white — it’s see-through, and their skin underneath is black.', subject: 'animals' },
  { q: 'Which animal has the longest memory saying — "an ___ never forgets"?', choices: ['Owl', 'Elephant', 'Tortoise', 'Dolphin'], answer: 1, context: '🐘 Remember this…', fact: 'Did you know? Elephants really do remember friends and waterholes for decades.', subject: 'animals' },
  { q: 'What is the only mammal that can truly fly?', choices: ['Flying squirrel', 'Bat', 'Ostrich', 'Sugar glider'], answer: 1, context: '🦇 Up at dusk…', fact: 'Did you know? Some bats can eat over 1,000 mosquitoes in a single hour. Asante, bats!', subject: 'animals' },

  // ── 🔢 Numbers (15) ────────────────────────────────────────────────
  { q: 'How many minutes are there in one hour?', choices: ['30', '60', '90', '100'], answer: 1, context: '⏰ Tick tock…', fact: 'Did you know? The 60-minute hour comes from ancient Babylon, over 4,000 years ago.', subject: 'numbers' },
  { q: 'What is 7 × 8?', choices: ['54', '58', '56', '64'], answer: 2, context: '✖️ Times tables…', fact: 'Did you know? 56 reversed is 65 — and 7 × 8 is famous for tricking even adults.', subject: 'numbers' },
  { q: 'How many sides does a hexagon have?', choices: ['5', '6', '7', '8'], answer: 1, context: '📐 Shape up…', fact: 'Did you know? Bees build hexagons because they hold the most honey with the least wax.', subject: 'numbers' },
  { q: 'What is half of 100?', choices: ['25', '40', '50', '60'], answer: 2, context: '➗ Split it…', fact: 'Did you know? "Fifty-fifty" means sharing something exactly in half — fair and square.', subject: 'numbers' },
  { q: 'How many days are in a leap year?', choices: ['364', '365', '366', '367'], answer: 2, context: '📅 Extra day…', fact: 'Did you know? Leap day babies born on 29 February only get a "real" birthday every 4 years.', subject: 'numbers' },
  { q: 'Which number is called a dozen?', choices: ['10', '12', '16', '20'], answer: 1, context: '🥚 At the market…', fact: 'Did you know? A "baker’s dozen" is 13 — old-time bakers added one extra to avoid selling short.', subject: 'numbers' },
  { q: 'What is 100 ÷ 4?', choices: ['20', '25', '30', '40'], answer: 1, context: '➗ Share fairly…', fact: 'Did you know? Dividing by 4 is just halving twice — 100 → 50 → 25.', subject: 'numbers' },
  { q: 'How many zeros are in one million?', choices: ['5', '6', '7', '8'], answer: 1, context: '💰 Big money…', fact: 'Did you know? Counting to a million out loud would take you about 3 weeks without sleeping.', subject: 'numbers' },
  { q: 'What comes next: 2, 4, 8, 16, …?', choices: ['20', '24', '32', '18'], answer: 2, context: '🧠 Spot the pattern…', fact: 'Did you know? Doubling grows shockingly fast — 30 doublings of 1 shilling passes a billion.', subject: 'numbers' },
  { q: 'How many hours are in a full day?', choices: ['12', '20', '24', '48'], answer: 2, context: '🌍 Round and round…', fact: 'Did you know? A day on Venus lasts longer than its whole year around the Sun.', subject: 'numbers' },
  { q: 'What is a shape with 3 sides called?', choices: ['Square', 'Triangle', 'Circle', 'Pentagon'], answer: 1, context: '📐 Three’s company…', fact: 'Did you know? Triangles are the strongest simple shape — that’s why bridges are full of them.', subject: 'numbers' },
  { q: 'What is 9 + 6?', choices: ['14', '15', '16', '17'], answer: 1, context: '➕ Quick maths…', fact: 'Did you know? A trick: take 1 from the 6 to make the 9 a 10, then 10 + 5 = 15.', subject: 'numbers' },
  { q: 'How many seconds are in one minute?', choices: ['60', '100', '30', '90'], answer: 0, context: '⏱️ Count it down…', fact: 'Did you know? A hummingbird beats its wings about 3,000 times in one minute.', subject: 'numbers' },
  { q: 'Which is the smallest two-digit number?', choices: ['11', '10', '12', '99'], answer: 1, context: '🔢 Think small…', fact: 'Did you know? Zero was invented later than the other digits — and changed maths forever.', subject: 'numbers' },
  { q: 'If you cut a pizza into 8 equal slices and eat 2, how many are left?', choices: ['4', '5', '6', '7'], answer: 2, context: '🍕 Yum yum…', fact: 'Did you know? Each slice is one eighth — you ate 2/8, which is the same as 1/4.', subject: 'numbers' },

  // ── 📖 Words (15) ──────────────────────────────────────────────────
  { q: 'What does "jambo" mean in Swahili?', choices: ['Goodbye', 'Hello', 'Thank you', 'Please'], answer: 1, context: '🇹🇿 Karibu…', fact: 'Did you know? Swahili is spoken by over 200 million people across East Africa.', subject: 'words' },
  { q: 'Which word is the opposite of "brave"?', choices: ['Strong', 'Kind', 'Afraid', 'Happy'], answer: 2, context: '💪 Opposites…', fact: 'Did you know? Being brave doesn’t mean you’re not afraid — it means you act even when you are.', subject: 'words' },
  { q: 'What do we call a word that sounds the same as another but means something different?', choices: ['A rhyme', 'A homophone', 'A verb', 'A vowel'], answer: 1, context: '🔤 Word play…', fact: 'Did you know? "Flower" and "flour" sound identical — one grows, one bakes.', subject: 'words' },
  { q: 'How many letters are in the English alphabet?', choices: ['24', '25', '26', '28'], answer: 2, context: '🔠 A to Z…', fact: 'Did you know? The most used letter in English is E — try writing a sentence without it!', subject: 'words' },
  { q: '"Asante sana" means…', choices: ['Good morning', 'Thank you very much', 'See you later', 'How are you'], answer: 1, context: '🙏 Manners matter…', fact: 'Did you know? Adding "sana" makes anything stronger in Swahili — asante sana = thanks a LOT.', subject: 'words' },
  { q: 'Which of these is a question word?', choices: ['Because', 'Why', 'And', 'But'], answer: 1, context: '❓ Ask away…', fact: 'Did you know? Curious kids ask about 100 questions a day — scientists say that’s how brains grow.', subject: 'words' },
  { q: 'What is a group of words that tells a complete idea called?', choices: ['A letter', 'A syllable', 'A sentence', 'A sound'], answer: 2, context: '✍️ Build it…', fact: 'Did you know? The shortest full sentence in English is just two letters: "Go."', subject: 'words' },
  { q: 'Which word rhymes with "light"?', choices: ['Lamp', 'Night', 'Dark', 'Shine'], answer: 1, context: '🎵 Rhyme time…', fact: 'Did you know? Rhymes help your brain remember — that’s why songs stick in your head.', subject: 'words' },
  { q: 'What do we call the name of a person, place or thing?', choices: ['A verb', 'An adjective', 'A noun', 'An adverb'], answer: 2, context: '📚 Grammar bites…', fact: 'Did you know? "Kaya" means home in several African languages — the coastal Mijikenda built sacred kaya villages.', subject: 'words' },
  { q: 'Which of these means very, very big?', choices: ['Tiny', 'Enormous', 'Narrow', 'Short'], answer: 1, context: '🐘 Size words…', fact: 'Did you know? English borrowed "enormous" from Latin — and "safari" from Swahili!', subject: 'words' },
  { q: 'What is the opposite of "generous"?', choices: ['Selfish', 'Cheerful', 'Honest', 'Quiet'], answer: 0, context: '💝 Heart words…', fact: 'Did you know? Studies show giving to others makes YOU happier too — generosity is a superpower.', subject: 'words' },
  { q: 'A word that describes an action, like "run" or "jump", is a…', choices: ['Noun', 'Verb', 'Adjective', 'Pronoun'], answer: 1, context: '🏃 Action words…', fact: 'Did you know? "Set" is one of the busiest words in English with hundreds of meanings.', subject: 'words' },
  { q: 'What does "rafiki" mean in Swahili?', choices: ['Teacher', 'Friend', 'Lion', 'Journey'], answer: 1, context: '🤝 Kind words…', fact: 'Did you know? The wise character Rafiki in The Lion King is literally named "friend" in Swahili.', subject: 'words' },
  { q: 'Which punctuation mark ends an excited sentence?', choices: ['A full stop', 'A comma', 'An exclamation mark', 'A question mark'], answer: 2, context: '❗ Feel it…', fact: 'Did you know? The exclamation mark may come from Latin "io" — a shout of joy — stacked vertically.', subject: 'words' },
  { q: 'What do we call a story that teaches a lesson, often with animals?', choices: ['A recipe', 'A fable', 'A diary', 'A list'], answer: 1, context: '🦊 Story time…', fact: 'Did you know? Aesop’s fables, like the Tortoise and the Hare, are over 2,500 years old.', subject: 'words' },

  // ── ⚽ Sports & fun (15) ───────────────────────────────────────────
  { q: 'How many players are on a football (soccer) team on the pitch?', choices: ['9', '10', '11', '12'], answer: 2, context: '⚽ Kick off…', fact: 'Did you know? Football is played by over 250 million people in more than 200 countries.', subject: 'sports & fun' },
  { q: 'In which sport do you serve, volley and smash over a high net with your hands?', choices: ['Tennis', 'Volleyball', 'Cricket', 'Hockey'], answer: 1, context: '🏐 Over the net…', fact: 'Did you know? Volleyball was invented in 1895 and was first called "mintonette".', subject: 'sports & fun' },
  { q: 'How often are the Olympic Games held?', choices: ['Every year', 'Every 2 years', 'Every 4 years', 'Every 10 years'], answer: 2, context: '🥇 Going for gold…', fact: 'Did you know? Tanzania’s Filbert Bayi set a world record in the 1,500m in 1974 that stood for years.', subject: 'sports & fun' },
  { q: 'What colour card sends a footballer off the pitch?', choices: ['Yellow', 'Red', 'Green', 'Blue'], answer: 1, context: '🟥 Rules are rules…', fact: 'Did you know? Red and yellow cards were inspired by traffic lights.', subject: 'sports & fun' },
  { q: 'Which sport uses a shuttlecock?', choices: ['Badminton', 'Squash', 'Table tennis', 'Golf'], answer: 0, context: '🏸 Light as a feather…', fact: 'Did you know? A smashed shuttlecock can fly over 400 km/h — faster than a race car.', subject: 'sports & fun' },
  { q: 'In chess, which piece can only move diagonally?', choices: ['Rook', 'Knight', 'Bishop', 'Queen'], answer: 2, context: '♟️ Your move…', fact: 'Did you know? The number of possible chess games is greater than the atoms in the observable universe.', subject: 'sports & fun' },
  { q: 'What is the fastest swimming stroke?', choices: ['Breaststroke', 'Backstroke', 'Butterfly', 'Front crawl'], answer: 3, context: '🏊 Splash…', fact: 'Did you know? Front crawl is also called freestyle because swimmers may choose any stroke — and always choose it.', subject: 'sports & fun' },
  { q: 'How many rings are on the Olympic flag?', choices: ['4', '5', '6', '7'], answer: 1, context: '🌈 Count the rings…', fact: 'Did you know? The five rings stand for the five inhabited continents, linked in friendship.', subject: 'sports & fun' },
  { q: 'Which country has won the most football World Cups?', choices: ['Germany', 'Argentina', 'Brazil', 'France'], answer: 2, context: '🏆 Champions…', fact: 'Did you know? Brazil has won 5 World Cups and is the only team to play in every single tournament.', subject: 'sports & fun' },
  { q: 'In which game do you knock down 10 pins with a ball?', choices: ['Bowling', 'Golf', 'Darts', 'Snooker'], answer: 0, context: '🎳 Strike…', fact: 'Did you know? Knocking all 10 pins with one roll is a strike — three in a row is called a turkey!', subject: 'sports & fun' },
  { q: 'What do runners pass to each other in a relay race?', choices: ['A flag', 'A baton', 'A ball', 'A ribbon'], answer: 1, context: '🏃 Team speed…', fact: 'Did you know? Relay teams can beat the world’s fastest solo runner — teamwork really is faster.', subject: 'sports & fun' },
  { q: 'Which board game features Mr. Monopoly and collecting rent?', choices: ['Ludo', 'Monopoly', 'Scrabble', 'Snakes & Ladders'], answer: 1, context: '🎲 Roll the dice…', fact: 'Did you know? The longest Monopoly game on record lasted 70 straight days.', subject: 'sports & fun' },
  { q: 'How many squares are on a chess board?', choices: ['36', '49', '64', '81'], answer: 2, context: '♟️ Check the board…', fact: 'Did you know? 64 squares, but over 300 billion possible ways to play just the first four moves.', subject: 'sports & fun' },
  { q: 'What sport is played at Wimbledon?', choices: ['Cricket', 'Rugby', 'Tennis', 'Golf'], answer: 2, context: '🎾 Quiet please…', fact: 'Did you know? Wimbledon players must wear almost entirely white — a rule from the 1800s.', subject: 'sports & fun' },
  { q: 'Which of these is a famous Tanzanian football derby?', choices: ['Simba vs Yanga', 'Ajax vs Feyenoord', 'Barcelona vs Real', 'Chiefs vs Pirates'], answer: 0, context: '🇹🇿 Derby day…', fact: 'Did you know? Simba vs Young Africans (Yanga) has packed Dar es Salaam stadiums for over 50 years.', subject: 'sports & fun' },

  // ── 🙏 Faith & family (15) ─────────────────────────────────────────
  { q: 'In the story of Noah, how did the animals enter the ark?', choices: ['One by one', 'Two by two', 'In tens', 'All at once'], answer: 1, context: '🚢 Story time…', fact: 'Did you know? The rainbow after the flood became a sign of promise and hope.', subject: 'faith & family' },
  { q: 'What is a good first step after a quarrel with your sibling?', choices: ['Ignore them forever', 'Say sorry and talk', 'Hide their toys', 'Shout louder'], answer: 1, context: '💛 Family first…', fact: 'Did you know? Saying sorry actually lowers stress for BOTH people — science agrees with grandma.', subject: 'faith & family' },
  { q: 'Which meal do many families share to start the day together?', choices: ['Supper', 'Lunch', 'Breakfast', 'Dessert'], answer: 2, context: '🍳 Rise and shine…', fact: 'Did you know? Kids who eat breakfast with family tend to do better at school — chapati counts!', subject: 'faith & family' },
  { q: 'What does "gratitude" mean?', choices: ['Being thankful', 'Being tired', 'Being fast', 'Being loud'], answer: 0, context: '🙏 Heart check…', fact: 'Did you know? Writing down 3 thankful things a day measurably boosts happiness — just like meeting prep!', subject: 'faith & family' },
  { q: 'In the famous story, who defeated the giant Goliath?', choices: ['Moses', 'David', 'Samson', 'Joseph'], answer: 1, context: '🪨 Small but mighty…', fact: 'Did you know? David was the youngest of eight brothers — never underestimate the little one.', subject: 'faith & family' },
  { q: 'What is the kind thing to do when a new kid joins your class?', choices: ['Ignore them', 'Laugh at them', 'Welcome them', 'Hide from them'], answer: 2, context: '🤝 Karibu…', fact: 'Did you know? "Karibu" — welcome — is one of the first words guests hear in a Tanzanian home.', subject: 'faith & family' },
  { q: 'How many days did God take to create the world in Genesis, before resting?', choices: ['3', '6', '7', '10'], answer: 1, context: '📖 In the beginning…', fact: 'Did you know? The seventh day of rest is where the idea of a weekly day off comes from.', subject: 'faith & family' },
  { q: 'What do we call the special promise two people make when they marry?', choices: ['A vow', 'A verse', 'A recipe', 'A rule'], answer: 0, context: '💍 Big promises…', fact: 'Did you know? Anniversaries celebrate keeping that promise — year after year after year.', subject: 'faith & family' },
  { q: 'Which of these shows respect to elders?', choices: ['Interrupting them', 'Greeting them politely', 'Walking away', 'Rolling your eyes'], answer: 1, context: '🧓 Heshima…', fact: 'Did you know? In Swahili culture, "shikamoo" is a special greeting of respect for elders.', subject: 'faith & family' },
  { q: 'What should you do when someone is talking to you?', choices: ['Look at your phone', 'Listen carefully', 'Sing loudly', 'Walk in circles'], answer: 1, context: '👂 All ears…', fact: 'Did you know? You have two ears and one mouth — a famous reminder to listen twice as much as you speak.', subject: 'faith & family' },
  { q: 'In the story, what swallowed Jonah?', choices: ['A lion', 'A great fish', 'A bear', 'An eagle'], answer: 1, context: '🐋 Deep waters…', fact: 'Did you know? Jonah spent three days inside before getting a second chance.', subject: 'faith & family' },
  { q: 'What is the best thing to share when your friend is sad?', choices: ['Your time and kindness', 'Your homework answers', 'Nothing', 'A scary story'], answer: 0, context: '🫂 Be there…', fact: 'Did you know? Just sitting quietly beside a sad friend releases comfort hormones in their brain.', subject: 'faith & family' },
  { q: 'Which word means working together as one?', choices: ['Teamwork', 'Homework', 'Network', 'Artwork'], answer: 0, context: '👨‍👩‍👧‍👦 Better together…', fact: 'Did you know? "Harambee" — pulling together — is a beloved East African word for teamwork.', subject: 'faith & family' },
  { q: 'What did the Good Samaritan do for the hurt stranger?', choices: ['Walked past', 'Stopped and helped', 'Called the police', 'Took his coat'], answer: 1, context: '💛 Love your neighbour…', fact: 'Did you know? "Samaritan" now means a kind helper in everyday English, thanks to this story.', subject: 'faith & family' },
  { q: 'Why do families hold a weekly meeting like yours?', choices: ['To grow closer and plan together', 'To watch more TV', 'To argue', 'To skip chores'], answer: 0, context: '🗓️ Sunday special…', fact: 'Did you know? Families who meet weekly report feeling more connected — you’re living proof.', subject: 'faith & family' },
];

/** Normalised fingerprint used for the no-repeat `seen` list. */
export function qotdFingerprint(q: string): string {
  return q.toLowerCase().replace(/[^a-z0-9]/g, '').slice(0, 80);
}
