'use client';

// Kaya Sparks · per-kid progress dashboard (/sparks/[kidId]/dashboard).
//
// Slice 5 (2026-05-27) — full surface:
//   • Time filter (Week / Month / Term / Year / All-time)
//   • KPI row: avg ⭐ · avg % · items captured · top area · ⭐ streak
//   • 10-week trend chart (count per week + ⭐ avg overlay)
//   • Category breakdown — horizontal bars per area
//   • AI Insights — 4 cards generated by /api/sparks/ai/insights
//
// Parent-only by route guard. Kids/helpers bounce back to /sparks/[kidId].
// Family roll-up + PDF term export + companion daily refresh land in
// Slice 5b.

import Link from 'next/link';
import { useEffect, useMemo, useState } from 'react';
import { useParams, useRouter } from 'next/navigation';
import { useAuth } from '@/contexts/AuthContext';
import { useFamily } from '@/contexts/FamilyContext';
import { useSparksFeatures } from '@/lib/sparks/gating';
import {
  subscribeToAcademicRecords, subscribeToAllKidItems,
  subscribeToKidRatings,
} from '@/lib/sparks/firestore';
import {
  categoryBreakdown, computeKpis, FILTER_LABELS, filterByDate,
  weeklyTrend, type SparksFilter,
} from '@/lib/sparks/dashboard';
import {
  getSparksInsights, type SparksInsights,
} from '@/lib/sparks/ai';
import {
  SPARKS_AREA_META, type SparksAcademicRecord, type SparksItem,
  type SparksItemArea, type SparksRating,
} from '@/lib/sparks/schema';

const FILTERS: Array<Exclude<SparksFilter, object>> = ['week', 'month', 'term', 'year', 'all'];

export default function KidSparksDashboardPage() {
  const params = useParams<{ kidId: string }>();
  const kidId = params?.kidId ?? '';
  const { profile } = useAuth();
  const { children } = useFamily();
  const router = useRouter();
  const features = useSparksFeatures();

  const kid = useMemo(() => children.find((c) => c.id === kidId), [children, kidId]);
  const familyId = profile?.familyId;
  const isParent = profile?.role === 'parent';

  useEffect(() => {
    if (profile && profile.role !== 'parent') router.replace(`/sparks/${kidId}`);
  }, [profile, kidId, router]);

  // ── Data streams ─────────────────────────────────
  const [items, setItems] = useState<SparksItem[]>([]);
  const [ratings, setRatings] = useState<SparksRating[]>([]);
  const [records, setRecords] = useState<SparksAcademicRecord[]>([]);

  useEffect(() => {
    if (!familyId || !kidId) return;
    return subscribeToAllKidItems(familyId, kidId, setItems);
  }, [familyId, kidId]);
  useEffect(() => {
    if (!familyId || !kidId) return;
    return subscribeToKidRatings(familyId, kidId, setRatings);
  }, [familyId, kidId]);
  useEffect(() => {
    if (!familyId || !kidId) return;
    return subscribeToAcademicRecords(familyId, kidId, setRecords);
  }, [familyId, kidId]);

  // ── Filter / derived ─────────────────────────────
  const [filter, setFilter] = useState<SparksFilter>('month');
  const itemsFiltered = useMemo(() => filterByDate(items, filter), [items, filter]);
  const ratingsFiltered = useMemo(() => filterByDate(ratings, filter), [ratings, filter]);
  const kpis = useMemo(() => computeKpis(itemsFiltered, ratingsFiltered), [itemsFiltered, ratingsFiltered]);
  const trend = useMemo(() => weeklyTrend(items, ratings, 10), [items, ratings]); // trend always 10-week regardless of filter
  const breakdown = useMemo(
    () => categoryBreakdown(itemsFiltered, ratingsFiltered, records.length),
    [itemsFiltered, ratingsFiltered, records.length],
  );

  // ── AI insights ──────────────────────────────────
  const [insights, setInsights] = useState<SparksInsights | null>(null);
  const [insightsState, setInsightsState] = useState<'idle' | 'loading' | 'ok' | 'skipped' | 'error'>('idle');

  // Fire once on mount + when kidId changes; debounce subsequent
  // refetches behind a manual "refresh" button so we don't burn the
  // model on every keystroke filter change.
  useEffect(() => {
    if (!kid || !kidId) return;
    let cancelled = false;
    void (async () => {
      setInsightsState('loading');
      const out = await getSparksInsights({
        kidName: kid.name,
        windowLabel: filterLabel(filter),
        itemCountsByArea: countByArea(itemsFiltered),
        recentRatings: ratingsFiltered.slice(0, 30).map((r) => ({
          date: r.date, area: areaForRating(r, itemsFiltered),
          title: titleForRating(r, itemsFiltered),
          stars: r.stars, percent: r.percent, notes: r.notes,
        })),
        recentItemTitles: itemsFiltered.slice(0, 30).map((i) => ({
          area: i.area, title: i.title, date: i.date,
        })),
        academicSnapshot: records.slice(0, 6).map((r) => ({
          term: r.term, year: r.year,
          subjects: r.subjects.map((s) => ({ name: s.name, grade: s.grade, percent: s.percent })),
        })),
      });
      if (cancelled) return;
      if ('skipped' in out && out.skipped) { setInsightsState('skipped'); setInsights(null); return; }
      if (!out.ok) { setInsightsState('error'); setInsights(null); return; }
      setInsightsState('ok'); setInsights(out.data);
    })();
    return () => { cancelled = true; };
    // intentionally NOT depending on filter — insights are a costly
    // call and the panel's content rarely shifts with the filter alone.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [kid?.name, kidId]);

  if (!isParent) return null;
  if (!kid || !familyId) {
    return <div className="min-h-screen bg-[#FBF7EE] grid place-items-center text-[#5A6488] text-sm">Loading…</div>;
  }

  return (
    <div className="min-h-[80vh] bg-[#FBF7EE] text-[#0F1F44]">
      <div className="mx-auto max-w-md sm:max-w-3xl lg:max-w-5xl xl:max-w-6xl px-5 lg:px-10 pt-6 pb-16">
        {/* Back to kid Sparks */}
        <Link
          href={`/sparks/${kid.id}`}
          className="inline-flex items-center gap-1.5 pl-2.5 pr-3.5 py-1.5 rounded-full bg-white border border-[rgba(15,31,68,0.08)] text-[#0F1F44] font-display font-extrabold text-[12px] no-underline hover:border-[#D4A847] transition-colors mb-4 print-hide"
        >
          <span className="text-[13px] leading-none opacity-60" aria-hidden>‹</span>
          <span>{kid.name}&apos;s Sparks</span>
        </Link>

        {/* Header */}
        <div className="flex items-baseline gap-3 mb-4 print-keep">
          <span className="text-3xl" aria-hidden>📊</span>
          <h1 className="font-display font-extrabold text-2xl lg:text-3xl tracking-tight m-0 flex-1">
            {kid.name}&apos;s progress
          </h1>
          <div className="flex items-center gap-1.5 print-hide">
            <Link
              href="/sparks/dashboard"
              className="hidden sm:inline-flex items-center gap-1.5 px-3 py-1.5 rounded-full text-[12px] font-bold bg-white border border-[rgba(15,31,68,0.08)] text-[#0F1F44] hover:border-[#D4A847] no-underline"
              title="See every kid in the family side by side"
            >
              👨‍👩‍👧‍👦 Family
            </Link>
            <button
              type="button"
              onClick={() => window.print()}
              className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-full text-[12px] font-bold bg-white border border-[rgba(15,31,68,0.08)] text-[#0F1F44] hover:border-[#D4A847]"
              title="Print or save as PDF — your browser handles it"
            >
              🖨 Print / PDF
            </button>
          </div>
        </div>

        {/* Time filter */}
        <div className="flex flex-wrap items-center gap-1.5 mb-5 print-hide">
          {FILTERS.map((f) => {
            const active = filter === f;
            return (
              <button
                key={f}
                type="button"
                onClick={() => setFilter(f)}
                className={`px-3 py-1.5 rounded-full text-[12px] font-bold transition-colors ${
                  active
                    ? 'bg-[#0F1F44] text-white'
                    : 'bg-white border border-[rgba(15,31,68,0.08)] text-[#0F1F44] hover:border-[#D4A847]'
                }`}
              >
                {FILTER_LABELS[f]}
              </button>
            );
          })}
        </div>

        {/* KPI row */}
        <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-5 gap-2.5 mb-6">
          <KpiCard
            label="Avg ⭐"
            value={kpis.ratingAgg.avgStars !== null ? kpis.ratingAgg.avgStars.toFixed(1) : '—'}
            chip={`${kpis.totalRatings} ratings`}
            tone="#FFF1C9" toneFg="#8A6800"
          />
          <KpiCard
            label="Avg %"
            value={kpis.ratingAgg.avgPercent !== null ? `${kpis.ratingAgg.avgPercent}%` : '—'}
            chip="quality + logic"
            tone="#E5D6FF" toneFg="#5A3CB8"
          />
          <KpiCard
            label="Items"
            value={String(kpis.totalItems)}
            chip="captured"
            tone="#FFE7E0" toneFg="#E85C5C"
          />
          <KpiCard
            label="Top area"
            value={kpis.topArea ? SPARKS_AREA_META[kpis.topArea].shortLabel : '—'}
            chip={kpis.topArea ? SPARKS_AREA_META[kpis.topArea].emoji : '·'}
            tone="#DDF5DF" toneFg="#2E7D34"
          />
          <KpiCard
            label="⭐ Streak"
            value={`${kpis.starStreakDays}d`}
            chip={kpis.starStreakDays > 0 ? '4★+ daily' : 'start one'}
            tone="#C9F0EC" toneFg="#1E7873"
          />
        </div>

        {/* Trend chart */}
        <SectionCard title="10-week trend" subtitle="Items captured per week · ⭐ average overlay">
          <TrendChart trend={trend} />
        </SectionCard>

        {/* Category breakdown */}
        <SectionCard title="By area" subtitle={`Counts in this ${filterLabel(filter).toLowerCase()} window`}>
          <CategoryBars rows={breakdown} />
        </SectionCard>

        {/* AI Insights */}
        <SectionCard
          title="✨ AI insights"
          subtitle={features.aiScan ? 'Refreshed when you open this page' : 'Upgrade to Kaya Home for AI insights'}
        >
          <AiInsightsPanel state={insightsState} insights={insights} />
        </SectionCard>

        {/* Family + PDF tiles — now live */}
        <div className="mt-6 grid grid-cols-1 sm:grid-cols-2 gap-3 print-hide">
          <Link
            href="/sparks/dashboard"
            className="bg-white border border-[rgba(15,31,68,0.08)] rounded-2xl p-4 hover:border-[#D4A847] no-underline"
          >
            <div className="text-[11px] font-extrabold uppercase tracking-[0.8px] text-[#5A6488]">Family roll-up</div>
            <div className="font-display font-extrabold text-[14px] text-[#0F1F44] mt-1">
              See every kid side by side →
            </div>
            <div className="text-[12px] text-[#5A6488] mt-1 leading-snug">
              Compare ⭐ + % across all kids on one page.
              {!features.familyRollup && ' Home+ feature — Nest sees an upgrade tile.'}
            </div>
          </Link>
          <button
            type="button"
            onClick={() => window.print()}
            className="text-left bg-white border border-[rgba(15,31,68,0.08)] rounded-2xl p-4 hover:border-[#D4A847]"
          >
            <div className="text-[11px] font-extrabold uppercase tracking-[0.8px] text-[#5A6488]">Term PDF</div>
            <div className="font-display font-extrabold text-[14px] text-[#0F1F44] mt-1">
              Print this dashboard → Save as PDF
            </div>
            <div className="text-[12px] text-[#5A6488] mt-1 leading-snug">
              Browser-native, no library — KPIs, trend, breakdown + AI insights all carry over.
            </div>
          </button>
        </div>
      </div>
    </div>
  );
}

// ── Section card chrome ─────────────────────────────────────────────

function SectionCard({ title, subtitle, children }: { title: string; subtitle?: string; children: React.ReactNode }) {
  return (
    <section className="bg-white border border-[rgba(15,31,68,0.08)] rounded-2xl p-4 lg:p-5 mb-3 lg:mb-4">
      <div className="mb-3">
        <div className="font-display font-extrabold text-[14.5px] text-[#0F1F44]">{title}</div>
        {subtitle && <div className="text-[11.5px] text-[#5A6488] mt-0.5">{subtitle}</div>}
      </div>
      {children}
    </section>
  );
}

// ── KPI card ────────────────────────────────────────────────────────

function KpiCard({
  label, value, chip, tone, toneFg,
}: {
  label: string;
  value: string;
  chip?: string;
  tone: string;
  toneFg: string;
}) {
  return (
    <div className="bg-white border border-[rgba(15,31,68,0.08)] rounded-2xl p-3 lg:p-4">
      <div className="text-[10px] font-extrabold uppercase tracking-[0.8px] text-[#5A6488]">{label}</div>
      <div className="font-display font-extrabold text-[22px] lg:text-[26px] text-[#0F1F44] leading-tight mt-1">
        {value}
      </div>
      {chip && (
        <div
          className="inline-block text-[10px] font-bold rounded-full px-2 py-0.5 mt-1.5"
          style={{ background: tone, color: toneFg }}
        >
          {chip}
        </div>
      )}
    </div>
  );
}

// ── Trend chart ─────────────────────────────────────────────────────

function TrendChart({ trend }: { trend: ReturnType<typeof weeklyTrend> }) {
  const maxCount = Math.max(1, ...trend.map((b) => b.count));
  return (
    <div>
      {/* Bars row */}
      <div className="flex items-end gap-1.5 h-32">
        {trend.map((b, idx) => {
          const heightPct = Math.round((b.count / maxCount) * 100);
          const fill = b.avgStars !== null && b.avgStars >= 4
            ? '#6BCB77' // green when high
            : b.avgStars !== null && b.avgStars >= 3
              ? '#FFD93D' // yellow when mid
              : '#FF6B6B'; // coral when low / no ratings
          const empty = b.count === 0;
          return (
            <div key={b.weekStart} className="flex-1 flex flex-col items-center justify-end h-full">
              <div className="text-[9px] font-bold text-[#5A6488] mb-1">
                {b.count > 0 ? b.count : ''}
              </div>
              <div
                className="w-full rounded-t-md transition-all"
                style={{
                  height: empty ? '6%' : `${Math.max(8, heightPct)}%`,
                  background: empty ? '#ECE4D3' : fill,
                  opacity: empty ? 0.6 : 1,
                }}
                title={`${b.label} · ${b.count} items${b.avgStars !== null ? ` · ⭐ ${b.avgStars}` : ''}`}
              />
              <div className={`text-[9px] mt-1 ${idx === trend.length - 1 ? 'font-extrabold text-[#0F1F44]' : 'text-[#5A6488]'}`}>
                {b.label}
              </div>
            </div>
          );
        })}
      </div>
      <div className="mt-3 flex items-center justify-end gap-3 text-[10px] text-[#5A6488]">
        <span className="inline-flex items-center gap-1"><span className="inline-block w-2.5 h-2.5 rounded bg-[#6BCB77]" />⭐ 4+</span>
        <span className="inline-flex items-center gap-1"><span className="inline-block w-2.5 h-2.5 rounded bg-[#FFD93D]" />⭐ 3+</span>
        <span className="inline-flex items-center gap-1"><span className="inline-block w-2.5 h-2.5 rounded bg-[#FF6B6B]" />⭐ &lt;3</span>
      </div>
    </div>
  );
}

// ── Category breakdown ──────────────────────────────────────────────

function CategoryBars({ rows }: { rows: ReturnType<typeof categoryBreakdown> }) {
  const maxCount = Math.max(1, ...rows.map((r) => r.count));
  return (
    <ul className="m-0 p-0 list-none space-y-2.5">
      {rows.map((r) => {
        const widthPct = Math.max(2, Math.round((r.count / maxCount) * 100));
        return (
          <li key={r.area} className="flex items-center gap-2.5">
            <div className="w-28 lg:w-36 text-[12.5px] font-bold text-[#0F1F44] flex items-center gap-1.5 shrink-0">
              <span aria-hidden>{r.emoji}</span>
              <span className="truncate">{r.label}</span>
            </div>
            <div className="flex-1 h-2.5 rounded-full bg-[#FBF7EE] overflow-hidden">
              <div
                className="h-full rounded-full transition-all"
                style={{ width: `${widthPct}%`, background: r.accent, opacity: r.count === 0 ? 0.25 : 0.9 }}
              />
            </div>
            <div className="w-24 text-right text-[11px] font-bold text-[#5A6488] shrink-0">
              {r.count} {r.avgStars !== null && <span className="text-[#8A6800]"> · ⭐ {r.avgStars}</span>}
            </div>
          </li>
        );
      })}
    </ul>
  );
}

// ── AI Insights panel ───────────────────────────────────────────────

function AiInsightsPanel({
  state, insights,
}: {
  state: 'idle' | 'loading' | 'ok' | 'skipped' | 'error';
  insights: SparksInsights | null;
}) {
  if (state === 'loading') {
    return (
      <div className="text-[12.5px] text-[#5A6488] py-3">
        Reading {`${kpiVerb()}`}…
      </div>
    );
  }
  if (state === 'skipped') {
    return (
      <div className="text-[12.5px] text-[#5A6488]">
        AI insights are off on this build (no ANTHROPIC_API_KEY). Capture + rate a few more items — once the key is live, this panel fills in.
      </div>
    );
  }
  if (state === 'error') {
    return <div className="text-[12.5px] text-[#A33A2A]">Couldn&apos;t reach the AI. Try refreshing the page in a moment.</div>;
  }
  if (!insights) {
    return <div className="text-[12.5px] text-[#5A6488]">No insights yet — capture + rate a few items to seed the panel.</div>;
  }
  return (
    <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
      <InsightCard tone="#DDF5DF" toneFg="#2E7D34" label="Strength" {...insights.strength} />
      <InsightCard tone="#FFF1C9" toneFg="#8A6800" label="Watch"    {...insights.watch} />
      <InsightCard tone="#E5D6FF" toneFg="#5A3CB8" label="Trend"    {...insights.trend} />
      <InsightCard tone="#C9F0EC" toneFg="#1E7873" label="Suggest"  {...insights.suggest} />
    </div>
  );
}

function InsightCard({
  label, tone, toneFg, title, body,
}: {
  label: string;
  tone: string;
  toneFg: string;
  title: string;
  body: string;
}) {
  return (
    <div className="rounded-2xl p-3.5 border border-[rgba(15,31,68,0.08)] bg-white">
      <span
        className="inline-block text-[10px] font-extrabold uppercase tracking-[0.8px] rounded-full px-2 py-0.5"
        style={{ background: tone, color: toneFg }}
      >
        {label}
      </span>
      <div className="font-display font-extrabold text-[13.5px] text-[#0F1F44] mt-2 leading-snug">{title}</div>
      <div className="text-[12px] text-[#5A6488] mt-1 leading-snug">{body}</div>
    </div>
  );
}

// ── Helpers ─────────────────────────────────────────────────────────

function filterLabel(filter: SparksFilter): string {
  if (typeof filter === 'string') return FILTER_LABELS[filter];
  return `Last ${filter.customDays} days`;
}

function countByArea(items: SparksItem[]): Record<SparksItemArea, number> {
  const out: Record<SparksItemArea, number> = {
    school_project: 0, home_project: 0, achievement: 0, sports_subscription: 0, revision: 0,
  };
  for (const it of items) out[it.area]++;
  return out;
}

function areaForRating(r: SparksRating, items: SparksItem[]): string {
  if (!r.item_id) return '—';
  const it = items.find((x) => x.id === r.item_id);
  return it?.area ?? '—';
}

function titleForRating(r: SparksRating, items: SparksItem[]): string {
  if (!r.item_id) return '—';
  return items.find((x) => x.id === r.item_id)?.title ?? '—';
}

// Tiny copy variant so the loading state doesn't read as a static
// status. Doesn't matter much; just nicer.
function kpiVerb(): string {
  const opts = ['the term', 'the snapshot', 'the room', 'the past few weeks'];
  return opts[Math.floor(Math.random() * opts.length)];
}
