// Kaya Business · AI image generation (server). Turns a kid's business name or
// project idea into a friendly logo / product picture — to spark imagination
// and lift their marketing. Uses OpenAI gpt-image-1.
//
// Trust + fallback like the other AI routes: no-ops cleanly when
// OPENAI_API_KEY is missing, so every screen still works without it. Returns a
// base64 data URL; the client uploads it to Storage (family-scoped) and saves
// the resulting URL — keeps generated bytes off our server.
//
// Safety: prompts are constrained to simple logos / product concepts — never
// real people or faces — and OpenAI's own moderation applies on top.

import { NextRequest, NextResponse } from 'next/server';

export const runtime = 'nodejs';
export const dynamic = 'force-dynamic';
export const maxDuration = 60;

const apiKey = process.env.OPENAI_API_KEY;

type ImageKind = 'logo' | 'product';

interface ImageBody {
  kind: ImageKind;
  /** The business name or project title. */
  subject: string;
  /** Optional extra context — type, what it sells, a short description. */
  detail?: string;
}

function buildPrompt(kind: ImageKind, subject: string, detail: string): string {
  const safe = `Friendly, cheerful, kid-appropriate. Flat simple cartoon/vector style, bright colors, clean plain background, centered. No text, no words, no real people, no faces, no brand logos.`;
  if (kind === 'logo') {
    return `A simple, playful LOGO ICON for a children's tiny business called "${subject}"${detail ? ` (${detail})` : ''}. A single clear symbol that represents it. ${safe}`;
  }
  return `A fun product/concept illustration for a kid's maker project: "${subject}"${detail ? ` (${detail})` : ''}. Show the thing itself, appealing and simple. ${safe}`;
}

export async function POST(req: NextRequest) {
  if (!apiKey) {
    return NextResponse.json({ skipped: true, reason: 'OPENAI_API_KEY not set' });
  }

  let body: ImageBody;
  try {
    body = (await req.json()) as ImageBody;
  } catch {
    return NextResponse.json({ error: 'Invalid JSON' }, { status: 400 });
  }

  const kind: ImageKind = body?.kind === 'product' ? 'product' : 'logo';
  const subject = (body?.subject || '').trim().slice(0, 80);
  const detail = (body?.detail || '').trim().slice(0, 160);
  if (!subject) return NextResponse.json({ error: 'Missing subject' }, { status: 400 });

  try {
    const r = await fetch('https://api.openai.com/v1/images/generations', {
      method: 'POST',
      headers: { Authorization: `Bearer ${apiKey}`, 'Content-Type': 'application/json' },
      body: JSON.stringify({
        model: 'gpt-image-1',
        prompt: buildPrompt(kind, subject, detail),
        size: '1024x1024',
        n: 1,
      }),
    });
    const j = await r.json();
    if (!r.ok) {
      return NextResponse.json({ error: j?.error?.message || 'Image generation failed' }, { status: r.status });
    }
    const b64 = j?.data?.[0]?.b64_json;
    if (!b64) return NextResponse.json({ error: 'No image returned' }, { status: 502 });
    return NextResponse.json({ image: `data:image/png;base64,${b64}` });
  } catch (e: unknown) {
    return NextResponse.json({ error: e instanceof Error ? e.message : 'Image generation failed' }, { status: 500 });
  }
}
